#!/bin/bash

TITLE="PDF - Word Counter"
notify () {
    notify-send "$TITLE" "$1"
    #terminal-notifier -title "$TITLE" -message "$2"
}

count () {
    pdftotext "$1" - | wc -c
}

cur_dir="$(cd `dirname ${BASH_SOURCE[0]}` && pwd)"

notify "$cur_dir"
exit # comment this line to execute the rest of the script


files=$(find "$cur_dir" -maxdepth 1 -type f | grep "pdf")

while IFS="\n" read file; do
    word_count=$(count "$file")
    filename="$(basename "$file")"
    echo "$filename: $word_count"
    notify "$filename: $word_count" 
done <<< "$files"

